export type Page =
  | 'dashboard'
  | 'finance-insight'
  | 'hourly-sales'
  | 'system-sales'
  | 'variance-checking'
  | 'menu-item'
  | 'pos-journal'
  | 'rof'
  | 'deposit'
  | 'maintenance'
  | 'settings'